workflows:
  android-workflow:
    name: Android Debug Build
    max_build_duration: 30
    environment:
      vars:
        ANDROID_BUILD_TYPE: debug
      java: 17
    scripts:
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - "reymarmurillofox@gmail.com"
